const SHIFT_WEEK_API_URL="https://script.google.com/macros/s/AKfycbyr8KW-_XZsWDpQ_BnjdLQpiawjvOAAz4jWI8HVYVbCd-iiFjd6cau84tegSkbF203g/exec";let currentWeekItems=[];
class ApiError extends Error{constructor(message,errorId=""){super(message||"処理に失敗しました");this.errorId=errorId||""}}
document.addEventListener("DOMContentLoaded",async()=>{previousWeekButton.onclick=()=>moveWeek(-7);nextWeekButton.onclick=()=>moveWeek(7);currentWeekButton.onclick=async()=>{setWeekMonday(getMonday(new Date()));await loadCurrentWeek()};reloadButton.onclick=loadCurrentWeek;createButton.onclick=createInitialWeek;weekMonday.onchange=async e=>{const d=parseLocalDate(e.target.value);if(!d)return;setWeekMonday(getMonday(d));await loadCurrentWeek()};setWeekMonday(getMonday(new Date()));await loadCurrentWeek()});
function parseLocalDate(t){const m=String(t||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}function formatLocalDate(d){return[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}function getMonday(d){const r=new Date(d.getFullYear(),d.getMonth(),d.getDate()),day=r.getDay();r.setDate(r.getDate()+(day===0?-6:1-day));return r}function addDays(d,n){const r=new Date(d);r.setDate(r.getDate()+n);return r}function setWeekMonday(d){weekMonday.value=formatLocalDate(d);const s=addDays(d,6);weekRange.textContent=`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日 ～ ${s.getFullYear()}年${s.getMonth()+1}月${s.getDate()}日`}async function moveWeek(n){const d=parseLocalDate(weekMonday.value);if(!d)return;setWeekMonday(addDays(d,n));await loadCurrentWeek()}
async function loadCurrentWeek(){setMessage("基本シフトを読み込んでいます。");try{const r=await jsonpRequest("week-list",null,"shiftWeekListCallback",{weekMonday:weekMonday.value});currentWeekItems=r.data||[];renderTable();setMessage(currentWeekItems.length?"基本シフトを読み込みました。":"この週の基本シフトはまだありません。")}catch(e){showApiError(e,"基本シフトの読み込みに失敗しました")}}
async function createInitialWeek(){if(!confirm(weekMonday.value+"の週について、規定値から基本シフトを作成しますか？"))return;createButton.disabled=true;const t=createButton.textContent;createButton.textContent="作成中...";try{const r=await jsonpRequest("week-create",{weekMonday:weekMonday.value},"shiftWeekCreateCallback");setMessage(r.message||"初回作成が完了しました。");await loadCurrentWeek()}catch(e){showApiError(e,"基本シフトの初回作成に失敗しました")}finally{createButton.disabled=false;createButton.textContent=t}}
function renderTable(){shiftWeekBody.innerHTML="";recordCount.textContent=currentWeekItems.length+"件";if(!currentWeekItems.length){document.querySelector(".table-scroll").classList.add("hidden");emptyArea.classList.remove("hidden");return}document.querySelector(".table-scroll").classList.remove("hidden");emptyArea.classList.add("hidden");currentWeekItems.forEach(i=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${esc(i.user)}</td><td>${esc(i.date)}</td><td>${esc(i.weekday)}</td><td>${esc(i.startTime)}</td><td>${esc(i.endTime)}</td><td>${esc(i.service)}</td><td>${esc(i.vehicle)}</td><td class="content-cell">${esc(i.content)}</td><td class="note-cell">${esc(i.note)}</td><td>${esc(i.staff1)}</td><td>${esc(i.staff2)}</td><td>${esc(i.staff3)}</td><td>${esc(i.staff4)}</td><td>${esc(i.status)}</td><td>${esc(i.publishStatus)}</td>`;shiftWeekBody.appendChild(tr)})}
function setMessage(m,err=false){messageArea.textContent=m;messageArea.className="message-area"+(err?" error":"")}function showApiError(e,h){setMessage(h+"："+(e.message||"不明なエラー")+(e.errorId?"　エラー番号："+e.errorId:""),true);alert(h+"\n\n"+(e.message||"不明なエラー")+(e.errorId?"\n\nエラー番号："+e.errorId:""))}
function jsonpRequest(action,payload=null,prefix="callback",extra={}){return new Promise((resolve,reject)=>{const cb=prefix+"_"+Date.now()+"_"+Math.floor(Math.random()*100000),s=document.createElement("script");let done=false;const clean=()=>{delete window[cb];s.remove()};const timer=setTimeout(()=>{if(done)return;done=true;clean();reject(new ApiError("GASの応答がタイムアウトしました"))},30000);window[cb]=r=>{if(done)return;done=true;clearTimeout(timer);clean();if(!r||r.success!==true){reject(new ApiError(r&&r.message?r.message:"処理に失敗しました",r&&r.errorId?r.errorId:""));return}resolve(r)};const p=new URLSearchParams({action,callback:cb,_:Date.now()});Object.entries(extra).forEach(([k,v])=>p.set(k,v));if(payload!==null)p.set("payload",JSON.stringify(payload));s.src=`${SHIFT_WEEK_API_URL}?${p}`;s.onerror=()=>{if(done)return;done=true;clearTimeout(timer);clean();reject(new ApiError("GASへ接続できませんでした"))};document.body.appendChild(s)})}function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
