(() => {
'use strict';
const S={weekStart:monday(new Date()),scope:'all',employee:user(),day:todayIndex(),data:null};
const $=id=>document.getElementById(id);
const E={week:$('weekLabel'),nav:$('daysNav'),title:$('dayTitle'),count:$('dayCount'),msg:$('message'),list:$('requestList'),scope:[...document.querySelectorAll('.scope-btn')],open:$('openRegister'),dialog:$('requestDialog'),form:$('requestForm'),close:$('closeDialog'),cancel:$('cancelRegister'),type:$('requestType'),targetField:$('targetShiftField'),targetId:$('targetShiftId'),date:$('targetDate'),client:$('clientName'),system:$('system'),service:$('service'),start:$('startTime'),end:$('endTime'),support:$('supportContent'),main:$('mainStaffName'),staffFields:$('staffChangeFields'),oldStaff:$('oldStaffName'),newStaff:$('newStaffName'),changeField:$('changeContentField'),change:$('changeContent'),reason:$('changeReason'),dest:$('destination'),appt:$('appointmentTime'),meet:$('meetingPlace'),note:$('note'),saveMsg:$('saveMessage'),save:$('saveRequest')};

E.scope.forEach(b=>b.addEventListener('click',async()=>{if(b.dataset.scope==='mine'&&!S.employee.id){alert('ログイン中の従業員IDが必要です。');return;}S.scope=b.dataset.scope;E.scope.forEach(x=>x.classList.toggle('active',x===b));await load();}));
E.open.addEventListener('click',()=>{resetForm();const d=S.data?.days?.[S.day];if(d?.date)E.date.value=d.date;E.dialog.showModal();});
E.close.addEventListener('click',()=>E.dialog.close());E.cancel.addEventListener('click',()=>E.dialog.close());E.type.addEventListener('change',formMode);
E.form.addEventListener('submit',saveRequest);
formMode();load().catch(err=>message('依頼情報を取得できませんでした。\n'+(err?.message||err)));

async function api(payload){const url=String(window.REQUEST_APP?.GAS_URL||'').trim();if(!url.endsWith('/exec'))throw new Error('request-view-config.js のGAS_URLを確認してください。');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
async function load(){message('依頼情報を取得しています...');const j=await api({action:'request.week',weekStart:S.weekStart,scope:S.scope,employeeId:S.employee.id});if(!j?.ok)throw new Error(j?.message||j?.error||'GASエラー');S.data=j;render();}
async function saveRequest(ev){ev.preventDefault();const t=E.type.value;if(t!=='追加'&&!E.targetId.value.trim()){saveMsg('対象シフトIDを入力してください。',true);return;}if(t==='担当変更'&&(!E.oldStaff.value.trim()||!E.newStaff.value.trim())){saveMsg('変更前担当・変更後担当を入力してください。',true);return;}E.save.disabled=true;saveMsg('登録しています...',false);try{const j=await api({action:'request.save',requestType:t,targetShiftId:E.targetId.value.trim(),reporterId:S.employee.id,reporterName:S.employee.name,clientName:E.client.value.trim(),system:E.system.value,service:E.service.value.trim(),targetDate:E.date.value,startTime:E.start.value,endTime:E.end.value,mainStaffName:E.main.value.trim(),oldStaffName:E.oldStaff.value.trim(),newStaffName:E.newStaff.value.trim(),destination:E.dest.value.trim(),appointmentTime:E.appt.value,meetingPlace:E.meet.value.trim(),supportContent:E.support.value.trim(),changeContent:E.change.value.trim(),changeReason:E.reason.value.trim(),note:E.note.value.trim()});if(!j?.ok)throw new Error(j?.message||j?.error||'登録失敗');saveMsg('登録しました。\n'+(j.requestId||''),false);await load();setTimeout(()=>E.dialog.close(),500);}catch(err){saveMsg('登録できませんでした。\n'+(err?.message||err),true);}finally{E.save.disabled=false;}}
function render(){const days=S.data?.days||[];if(!days.length){message('対象週のデータがありません。');return;}E.week.textContent=`${label(days[0].date)}〜${label(days[6].date)}`;E.nav.innerHTML=days.map((d,i)=>{const c=['day-btn'];if(i===S.day)c.push('active');if(i===5)c.push('saturday');if(i===6)c.push('sunday');if(d.date===dateString(new Date()))c.push('today');return `<button type="button" class="${c.join(' ')}" data-i="${i}">${esc(d.weekday)}<span class="date">${esc(d.dateLabel)}</span></button>`;}).join('');[...E.nav.querySelectorAll('.day-btn')].forEach(b=>b.addEventListener('click',()=>{S.day=Number(b.dataset.i);render();}));const d=days[S.day];E.title.textContent=['月曜日','火曜日','水曜日','木曜日','金曜日','土曜日','日曜日'][S.day];E.count.textContent=`${d.items.length}件`;E.msg.hidden=true;E.list.innerHTML=d.items.length?d.items.map(card).join(''):`<div class="empty">${S.scope==='mine'?'この日の自分に関係する依頼はありません':'この日の依頼情報はありません'}</div>`;}
function card(x){const rows=[];if(x.requestType==='担当変更'){const s=[x.oldStaffName||'',x.newStaffName||''].filter(Boolean).join(' → ');if(s)rows.push(['担当変更',s]);}else if(x.requestType==='変更'){if(x.changeContent)rows.push(['変更内容',x.changeContent]);}else if(x.mainStaffName)rows.push(['担当',x.mainStaffName]);if(x.destination)rows.push(['行先',x.appointmentTime?`${x.destination}　予約 ${x.appointmentTime}`:x.destination]);if(x.meetingPlace)rows.push(['待合せ',x.meetingPlace]);if(x.changeReason)rows.push(['理由',x.changeReason]);return `<article class="card"><div class="top"><div class="time">${esc(range(x.startTime,x.endTime))}</div><div class="name">${esc(x.clientName||'')}</div><div class="badge ${badge(x.requestType)}">${esc(x.requestType||'')}</div></div><div class="service"><b>${esc(x.service||'')}</b>${esc(x.supportContent||'')}</div><div class="report"><span>報告者</span><b>${esc(x.reporterName||'')}</b></div>${rows.length?`<div class="meta">${rows.map(r=>`<div class="meta-row"><span class="label">${esc(r[0])}</span><span class="value">${esc(r[1])}</span></div>`).join('')}</div>`:''}${x.note?`<div class="memo">${esc(x.note)}</div>`:''}</article>`;}
function formMode(){const t=E.type.value;E.targetField.hidden=t==='追加';E.staffFields.hidden=t!=='担当変更';E.changeField.hidden=t!=='変更';}
function resetForm(){E.form.reset();E.type.value='追加';E.saveMsg.hidden=true;formMode();}
function saveMsg(t,e){E.saveMsg.hidden=false;E.saveMsg.textContent=t;E.saveMsg.style.color=e?'#c62828':'#1f2933';}
function message(t){E.list.innerHTML='';E.msg.hidden=false;E.msg.textContent=t;}
function badge(t){return t==='追加'?'add':t==='キャンセル'?'cancel':t==='担当変更'?'staff':'change';}
function range(a,b){return a&&b?`${a}–${b}`:(a||b||'時間未定');}
function user(){const p=new URLSearchParams(location.search);if(p.get('employeeId'))return{id:p.get('employeeId')||'',name:p.get('employeeName')||''};try{const u=JSON.parse(localStorage.getItem('currentUser')||'null');return{id:String(u?.employeeId||u?.id||''),name:String(u?.name||u?.employeeName||'')};}catch(_){return{id:'',name:''};}}
function monday(d){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());const day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return dateString(x);}function todayIndex(){const d=new Date().getDay();return d===0?6:d-1;}function dateString(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}function label(s){const m=String(s||'').match(/^\d{4}-(\d{2})-(\d{2})$/);return m?`${Number(m[1])}/${Number(m[2])}`:s||'';}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
})();
